# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5549f1ac609a9eaa280f70b81cf9b3f4a9a7cf4b697722cbeb3b63572f1b7f29bb9d6afe8cb6357e5c761347f6a799940725627b3dd3e9e35b308dd7d5ca135d

test:
  secret_key_base: 7d5bf7c46ac0d3de59e2b3f710610637a6435bcc7ce77dda52405720804c08fa43c46cdb6e8013bf24f14e81fae53cf67b0d5c6271f79d59f1bec7c91317604a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
